NAME="Test Expressions"
TIER="beginner"
NEEDS_DIR="true"
VALIDATION_TYPE="script"
VALIDATION_SCRIPT="validate.sh"
FAIL_MSG="Did not correctly test for file existence."
PASS_MSG="Nice! You used test expressions."
TOOL_CMD="bash"
