NAME="getopts"
TIER="master"
NEEDS_DIR="true"
TOOL_CMD="bash"
VALIDATION_TYPE="script"
VALIDATION_SCRIPT="validate.sh"
FAIL_MSG="Argument parsing with getopts was incorrect."
PASS_MSG="getopts parsing works."
