NAME="Health checks"
TIER="master"
NEEDS_DIR="true"
TOOL_CMD="bash"
VALIDATION_TYPE="script"
VALIDATION_SCRIPT="validate.sh"
FAIL_MSG="Health-check image/container was not configured correctly."
PASS_MSG="Health checks configured."
