NAME="Dockerfile basics"
TIER="intermediate"
NEEDS_DIR="true"
TOOL_CMD="bash"
VALIDATION_TYPE="script"
VALIDATION_SCRIPT="validate.sh"
FAIL_MSG="Dockerfile basics image was not built correctly."
PASS_MSG="You wrote and built a basic Dockerfile."
