NAME="virsh attach-interface"
TIER="intermediate"
TOOL_CMD="bash"
VALIDATION_TYPE="script"
VALIDATION_SCRIPT="validate.sh"
FAIL_MSG="Attach a network interface to the domain."
PASS_MSG="Interface attached!"
