NAME="Multi-stage builds"
TIER="master"
NEEDS_DIR="true"
TOOL_CMD="bash"
VALIDATION_TYPE="script"
VALIDATION_SCRIPT="validate.sh"
FAIL_MSG="Multi-stage Dockerfile/build requirements were not met."
PASS_MSG="You created a multi-stage build."
