NAME="Container networking"
TIER="advanced"
NEEDS_DIR="true"
TOOL_CMD="bash"
VALIDATION_TYPE="script"
VALIDATION_SCRIPT="validate.sh"
FAIL_MSG="Client networking was not validated successfully."
PASS_MSG="Containers communicated on a custom network."
