NAME="Environment variables"
TIER="intermediate"
TOOL_CMD="bash"
VALIDATION_TYPE="script"
VALIDATION_SCRIPT="validate.sh"
FAIL_MSG="Set environment variables in a unit."
PASS_MSG="Environment configured!"
