NAME="/proc/meminfo and /proc/cpuinfo"
TIER="intermediate"
TOOL_CMD="bash"
VALIDATION_TYPE="script"
VALIDATION_SCRIPT="validate.sh"
FAIL_MSG="Gather system hardware info."
PASS_MSG="System info gathered!"
