NAME="virsh pool-list"
TIER="intermediate"
TOOL_CMD="bash"
VALIDATION_TYPE="script"
VALIDATION_SCRIPT="validate.sh"
FAIL_MSG="List storage pools with virsh pool-list."
PASS_MSG="Listed storage pools!"
